// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: csvc_propose.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CsvcPropose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 跨分片的交易
	CrossTx []byte `protobuf:"bytes,1,opt,name=crossTx,proto3" json:"crossTx,omitempty"`
	// The raw signatures   原始签名
	Signatures []byte `protobuf:"bytes,2,opt,name=signatures,proto3" json:"signatures,omitempty"`
	// The IDs of the signers  签名者的id
	Shard uint64 `protobuf:"varint,3,opt,name=shard,proto3" json:"shard,omitempty"`
}

func (x *CsvcPropose) Reset() {
	*x = CsvcPropose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csvc_propose_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsvcPropose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvcPropose) ProtoMessage() {}

func (x *CsvcPropose) ProtoReflect() protoreflect.Message {
	mi := &file_csvc_propose_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvcPropose.ProtoReflect.Descriptor instead.
func (*CsvcPropose) Descriptor() ([]byte, []int) {
	return file_csvc_propose_proto_rawDescGZIP(), []int{0}
}

func (x *CsvcPropose) GetCrossTx() []byte {
	if x != nil {
		return x.CrossTx
	}
	return nil
}

func (x *CsvcPropose) GetSignatures() []byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *CsvcPropose) GetShard() uint64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

var File_csvc_propose_proto protoreflect.FileDescriptor

var file_csvc_propose_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x73, 0x76, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5e, 0x0a, 0x0c, 0x63, 0x73, 0x76,
	0x63, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x6f,
	0x73, 0x73, 0x54, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x72, 0x6f, 0x73,
	0x73, 0x54, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_csvc_propose_proto_rawDescOnce sync.Once
	file_csvc_propose_proto_rawDescData = file_csvc_propose_proto_rawDesc
)

func file_csvc_propose_proto_rawDescGZIP() []byte {
	file_csvc_propose_proto_rawDescOnce.Do(func() {
		file_csvc_propose_proto_rawDescData = protoimpl.X.CompressGZIP(file_csvc_propose_proto_rawDescData)
	})
	return file_csvc_propose_proto_rawDescData
}

var file_csvc_propose_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_csvc_propose_proto_goTypes = []interface{}{
	(*CsvcPropose)(nil), // 0: msg.csvc_propose
}
var file_csvc_propose_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_csvc_propose_proto_init() }
func file_csvc_propose_proto_init() {
	if File_csvc_propose_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csvc_propose_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsvcPropose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csvc_propose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_csvc_propose_proto_goTypes,
		DependencyIndexes: file_csvc_propose_proto_depIdxs,
		MessageInfos:      file_csvc_propose_proto_msgTypes,
	}.Build()
	File_csvc_propose_proto = out.File
	file_csvc_propose_proto_rawDesc = nil
	file_csvc_propose_proto_goTypes = nil
	file_csvc_propose_proto_depIdxs = nil
}
