// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: quest.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrossTx []byte `protobuf:"bytes,1,opt,name=crossTx,proto3" json:"crossTx,omitempty"`
}

func (x *Quest) Reset() {
	*x = Quest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest) ProtoMessage() {}

func (x *Quest) ProtoReflect() protoreflect.Message {
	mi := &file_quest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest.ProtoReflect.Descriptor instead.
func (*Quest) Descriptor() ([]byte, []int) {
	return file_quest_proto_rawDescGZIP(), []int{0}
}

func (x *Quest) GetCrossTx() []byte {
	if x != nil {
		return x.CrossTx
	}
	return nil
}

var File_quest_proto protoreflect.FileDescriptor

var file_quest_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x21, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x72, 0x6f, 0x73, 0x73, 0x54, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x72,
	0x6f, 0x73, 0x73, 0x54, 0x78, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quest_proto_rawDescOnce sync.Once
	file_quest_proto_rawDescData = file_quest_proto_rawDesc
)

func file_quest_proto_rawDescGZIP() []byte {
	file_quest_proto_rawDescOnce.Do(func() {
		file_quest_proto_rawDescData = protoimpl.X.CompressGZIP(file_quest_proto_rawDescData)
	})
	return file_quest_proto_rawDescData
}

var file_quest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_quest_proto_goTypes = []interface{}{
	(*Quest)(nil), // 0: msg.quest
}
var file_quest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quest_proto_init() }
func file_quest_proto_init() {
	if File_quest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quest_proto_goTypes,
		DependencyIndexes: file_quest_proto_depIdxs,
		MessageInfos:      file_quest_proto_msgTypes,
	}.Build()
	File_quest_proto = out.File
	file_quest_proto_rawDesc = nil
	file_quest_proto_goTypes = nil
	file_quest_proto_depIdxs = nil
}
