// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: config/client-config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientDataConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Protocol specific configuration
	Info *ProtoInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	// Network Configuration
	NetConfig *NetConfig `protobuf:"bytes,2,opt,name=NetConfig,proto3" json:"NetConfig,omitempty"`
	// Cryptographic configuration
	CryptoCon *CryptoConfig `protobuf:"bytes,4,opt,name=CryptoCon,proto3" json:"CryptoCon,omitempty"`
}

func (x *ClientDataConfig) Reset() {
	*x = ClientDataConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_client_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataConfig) ProtoMessage() {}

func (x *ClientDataConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_client_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataConfig.ProtoReflect.Descriptor instead.
func (*ClientDataConfig) Descriptor() ([]byte, []int) {
	return file_config_client_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientDataConfig) GetInfo() *ProtoInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ClientDataConfig) GetNetConfig() *NetConfig {
	if x != nil {
		return x.NetConfig
	}
	return nil
}

func (x *ClientDataConfig) GetCryptoCon() *CryptoConfig {
	if x != nil {
		return x.CryptoCon
	}
	return nil
}

var File_config_client_config_proto protoreflect.FileDescriptor

var file_config_client_config_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x1a, 0x10, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a,
	0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x25, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x09, 0x4e, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x09,
	0x4e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x09, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x6f, 0x6e, 0x42, 0x09, 0x5a,
	0x07, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_client_config_proto_rawDescOnce sync.Once
	file_config_client_config_proto_rawDescData = file_config_client_config_proto_rawDesc
)

func file_config_client_config_proto_rawDescGZIP() []byte {
	file_config_client_config_proto_rawDescOnce.Do(func() {
		file_config_client_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_client_config_proto_rawDescData)
	})
	return file_config_client_config_proto_rawDescData
}

var file_config_client_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_client_config_proto_goTypes = []interface{}{
	(*ClientDataConfig)(nil), // 0: config.ClientDataConfig
	(*ProtoInfo)(nil),        // 1: config.ProtoInfo
	(*NetConfig)(nil),        // 2: config.NetConfig
	(*CryptoConfig)(nil),     // 3: config.CryptoConfig
}
var file_config_client_config_proto_depIdxs = []int32{
	1, // 0: config.ClientDataConfig.Info:type_name -> config.ProtoInfo
	2, // 1: config.ClientDataConfig.NetConfig:type_name -> config.NetConfig
	3, // 2: config.ClientDataConfig.CryptoCon:type_name -> config.CryptoConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_client_config_proto_init() }
func file_config_client_config_proto_init() {
	if File_config_client_config_proto != nil {
		return
	}
	file_cryptoconf_proto_init()
	file_config_protocol_proto_init()
	file_network_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_config_client_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_client_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_client_config_proto_goTypes,
		DependencyIndexes: file_config_client_config_proto_depIdxs,
		MessageInfos:      file_config_client_config_proto_msgTypes,
	}.Build()
	File_config_client_config_proto = out.File
	file_config_client_config_proto_rawDesc = nil
	file_config_client_config_proto_goTypes = nil
	file_config_client_config_proto_depIdxs = nil
}
